### ISSUE TITLE
原神米油社签到显示成功，实际奖励没有到账，米友社app还可以签到

### ISSUE THREAD

**Issue by dmdada** [asadahimeka/userscripts#1]
原神米油社签到显示成功，实际奖励没有到账，米友社app还可以签到

**Comment by asadahimeka** [comment]
<s>可能是 cookie 里没有 cookie_token 这一项，或者 DS 算的不对了，或者米游社限制了网页端调用；
网页端来说还是限制比较多，建议使用云函数解决方案，Github 上搜 [genshin](https://github.com/search?q=genshin) 找找</s>

**Comment by asadahimeka** [comment]
@dmdada  我又下回了米游社 APP，看到好像从18号开始就失效了，应该是米游社添加了人机验证；因为我已经退坑了，目前并不打算继续维护这个脚本了，可以看看 python 云函数他们是否有解决方案，我觉得暂时是无解了[摊手]

**Comment by asadahimeka** [comment]
https://github.com/Womsxd/AutoMihoyoBBS/issues/179

**Comment by asadahimeka** [comment]
Womsxd/AutoMihoyoBBS/issues/179
